server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/oms_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

outbound:
  identity:
    client-id: "350237683034-u8nbbb50l61a7j072mrnjgf8vgec63oe.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGwxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 86400 # in second
  refreshable-duration: 259200 # in seconds

app:
  services:
    profile: http://localhost:8081/profile

admin:
  username: admin
  password: anhyeuem