server:
  port: 8084
  servlet:
    context-path: /comment

spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/comment-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    profile:
      url: http://localhost:8081/profile