name: open-msocial
version: '3.8'

services:
  # MySQL Databases
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    
  # MongoDB
  mongodb:
    image: mongo:8.0.1-noble
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      
  # Kafka
  kafka:
    image: 'bitnami/kafka:3.8.0'
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      
  # Backend Services
  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/oms_identity
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - APP_SERVICES_PROFILE=http://profile-service:8081/profile
      
  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/oms_user
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/notification-service?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      
  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/post-service?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - APP_SERVICES_PROFILE_URL=http://profile-service:8081/profile
      
  comment-service:
    build: ./comment-service
    container_name: comment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/comment-service?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - APP_SERVICES_PROFILE_URL=http://profile-service:8081/profile
      
  media-service:
    build: ./media-service
    container_name: media-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/oms_media
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - APP_SERVICES_PROFILE_URL=http://profile-service:8081/profile
      - APP_SERVICES_POST_URL=http://post-service:8083/post
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES[0].URI=http://identity-service:8080
      - SPRING_CLOUD_GATEWAY_ROUTES[1].URI=http://profile-service:8081
      - SPRING_CLOUD_GATEWAY_ROUTES[2].URI=http://notification-service:8082
      - SPRING_CLOUD_GATEWAY_ROUTES[3].URI=http://post-service:8083
      - SPRING_CLOUD_GATEWAY_ROUTES[4].URI=http://comment-service:8084
      - SPRING_CLOUD_GATEWAY_ROUTES[5].URI=http://media-service:8085
      
  # Frontend
  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "80:80"